### ISSUE TITLE
Support RadioHead library

### ISSUE THREAD

**Issue by ncolomer** [ivankravets/platformio-libmirror#1]
The [RadioHead](http://www.airspayce.com/mikem/arduino/RadioHead/index.html) library is an abstraction to help user implement wireless communication over RF modules (such as nRF24L01+). 
It is under Open Source Licensing GPL V2. Unfortunately, I did not found any source code repository (but sources are available for download).

**Comment by ivankravets** [comment]
Done. Thanks :+1: 
* [library.json](https://github.com/ivankravets/platformio-libmirror/blob/master/configs/radiohead.json)
* [Library Registry](http://platformio.org/#!/lib/show/124/RadioHead)
